---
title: "BatterBreakdown"
author: "Colin Sanders"
date: "2023-09-03"
output: pdf_document
---

```{r setup, include=FALSE}
library(baseballr)
library(ggplot2)
library(viridis)
table=chadwick_player_lu()
table=subset(table, pro_played_last > "2016")
table=subset(table, key_mlbam > 0)
player_id<-function(last_name, first_name, data) 
  {id<- table$key_mlbam[table$name_last == last_name & table$name_first == first_name]
if (length(id) == 0) 
{return("player not found")} 
  else{ return(id)}}
```

```{r message=FALSE, warning=FALSE}
Player<-player_id("Olson", "Matt", table)
dat<-scrape_statcast_savant(
  start_date = '2023-03-25',
  end_date = Sys.Date(),
  playerid = Player,
  player_type = "batter")
```

```{r spray chart warning=FALSE}
hit_colors <- c(
     "single" = "blue",
     "double" = "green",
     "triple" = "orange",
     "home_run" = "red", 
     "field_out" = "yellow",
     "sac_fly" = "yellow",
     "grounded_into_double_play" = "yellow",
     "fielders_choice" = "yellow",
     "force_out" = "yellow"
)

spray<-ggspraychart(
  dat,
  x_value = "hc_x",
  y_value = "-hc_y",
  fill_value = "events",
  fill_palette = hit_colors,
  fill_legend_title = NULL,
  density = FALSE,
  bin_size = 15,
  point_alpha = 0.75,
  point_size = 2,
  frame = NULL
)
spray
```

